### PR TITLE
Added help command using embeds

### PR DESCRIPTION
**Pull request by Likey00**
Simple help command which should be updated every time someone codes a command

### CODE REVIEW

**Comment by rosalogia** [comment]
Would it make sense to redesign the way the _content_ for each command's help message is retrieved, so as to put more responsibility on the cog developer? Right now, everyone who develops a cog has to edit this particular function to incorporate their cog's commands into the help message. That might not be ideal. We might prefer a way for cog developers to write their own help messages [in a pre-specified format] and then collect and display those messages in this particular function. Does that make sense?

**Comment by rosalogia** [comment]
A possible implementation of the above suggestion might involve strictly enforcing a standard for docstrings on any functions with the `@commands.command()` decorator above it, and then collecting those docstrings and presenting them in our help command.

**Comment by Likey00** [comment]
Not really, are you suggesting that it somehow retrieves the command from other cogs and incorporates the text? Let me know if you have a way to do this

**Comment by Likey00** [comment]
Help command automatically updates with docstrings now :)

**Review by rosalogia — APPROVED** [review]
Incredible :+1:

**Pull request merged**
